#FROM liferay-base:7.4.3.102

# Common configs/properties
#COPY --chown=liferay:liferay configs/common/ ${LIFERAY_HOME}/
#COPY --chown=liferay:liferay configs/local/ ${LIFERAY_HOME}/

# java-debug
#EXPOSE 8000

# Custom entrypoint which handles artifacts deployment
#COPY --chown=liferay:liferay scripts/liferay-entrypoint.sh /opt/liferay/liferay-entrypoint.sh
#RUN chmod +x /opt/liferay/liferay-entrypoint.sh
#ENTRYPOINT ["/opt/liferay/liferay-entrypoint.sh"]
